#!/bin/bash

if [[ -n "$BUILD_TYPE" ]]; then
    case $BUILD_TYPE in
        [Dd]ebug)
            BUILD_TYPE=Debug
            ;;
        [Rr]elease)
            BUILD_TYPE=Release
            ;;
        *)
            echo "Unacceptable value BUILD_TYPE=${BUILD_TYPE}, supported are Debug|Release"
            exit 1
            ;;
    esac
fi

cat << EOF > Makefile.defs
# Autogenerated by configure.sh
# Do not edit manually!

RESULTS_DIR     = ${RESULTS_DIR:-_result}
BUILD_TYPE      = ${BUILD_TYPE:-Debug}
EOF

# Log contents
echo "Makefile.defs contents:"
e=$'\033'
cat Makefile.defs | sed "s/#.*/${e}[33m\0${e}[0m/"
